package:
  name: pyeulercurves
  version: 0.1

source:
  path: ..

build:
  number: 0
  script: python -m pip install . -vvv

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - cmake
    - ninja

  host:
    - python
    - pip

  run:
    - python
    - numpy >=1.19
    - matplotlib >=3.3
    - scikit-learn >=0.23


test:
  imports:
    - pyEulerCurves
  source_files:
    - tests
  commands:
    - python tests/test.py

about:
  summary: A CMake example project built with pybind11.
  license_file: LICENSE
